/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.HoaDonChiTiet;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import service.HoaDonChiTiet_service;
import service.HoaDon_Service;

/**
 *
 * @author Asus
 */
public class Lich_Su_Hoa_Don extends javax.swing.JPanel {

    HoaDonChiTiet_service hdct_sv = new HoaDonChiTiet_service();
    HoaDon_Service hdsv = new HoaDon_Service();
    HoaDon hd = new HoaDon();
    DefaultTableModel model;
    int index = -1;
    int a = 1;
    int b = 2;
    int id = -2;

    /**
     * Creates new form Lich_Su_Hoa_Don
     */
    public Lich_Su_Hoa_Don() {
        initComponents();
        fillTable(hdsv.LichSuHoaDon(a, b));
        Jpanel_hoadonct.setVisible(false);
        btn_ct.setVisible(false);
        btn_new.setVisible(false);
        name();
        name1();
    }

    void name() {
        model = (DefaultTableModel) tbl_bang.getModel();
        String[] row = new String[]{
            "ID", "ma hoa don", "ten nguoi ban", "ten nguoi mua", "ngay ban", "tong tien", "trang thai"
        };
        model.setColumnIdentifiers(row);
    }

    void name1() {
        model = (DefaultTableModel) tbl_hdct.getModel();
        String[] row = new String[]{
            "lOAI SP", "TEN SP", "THUONG HIEU ", "MAU SAC", "CHAT LIEU", "DO CAN", "GIA", "SO LUONG", "MO TA"
        };
        model.setColumnIdentifiers(row);
    }

    void fillTable(List<HoaDon> list) {
        model = (DefaultTableModel) tbl_bang.getModel();
        model.setRowCount(0);
        list = hdsv.LichSuHoaDon(a, b);
        for (HoaDon hoaDon : list) {
            model.addRow(hoaDon.todata_lshd());
        }
    }

    boolean check() {
        boolean isValid = true;
        Date ngaythang = date_1.getDate();
         Date ngaythang1 = Date_2.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);

        if (ngaythang == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày bắt đầu");
            isValid = false;
        } else {
            if (sdf.format(ngaythang).isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày bắt đầu");
                isValid = false;
            }
        }
        if (ngaythang1 == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày kết thúc");
            isValid = false;
        } else {
            if (sdf.format(ngaythang1).isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày kết thúc");
                isValid = false;
            }
        }
        return isValid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        color1 = new com.raven.form.Color();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bang = new javax.swing.JTable();
        date_1 = new com.toedter.calendar.JDateChooser();
        Date_2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        Jpanel_hoadonct = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_hdct = new javax.swing.JTable();
        btn_ct = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        color1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lịch Sử Hóa Đơn"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_bang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bang);
        if (tbl_bang.getColumnModel().getColumnCount() > 0) {
            tbl_bang.getColumnModel().getColumn(0).setResizable(false);
            tbl_bang.getColumnModel().getColumn(1).setResizable(false);
            tbl_bang.getColumnModel().getColumn(2).setResizable(false);
            tbl_bang.getColumnModel().getColumn(3).setResizable(false);
            tbl_bang.getColumnModel().getColumn(4).setResizable(false);
            tbl_bang.getColumnModel().getColumn(5).setResizable(false);
            tbl_bang.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 847, 170));

        date_1.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(date_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 250, 40));

        Date_2.setDateFormatString("dd/MM/yyyy\n");
        jPanel1.add(Date_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 260, 40));

        jLabel1.setText("Đến");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 39, 22));

        Jpanel_hoadonct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_hdct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_hdct);
        if (tbl_hdct.getColumnModel().getColumnCount() > 0) {
            tbl_hdct.getColumnModel().getColumn(0).setResizable(false);
            tbl_hdct.getColumnModel().getColumn(1).setResizable(false);
            tbl_hdct.getColumnModel().getColumn(2).setResizable(false);
            tbl_hdct.getColumnModel().getColumn(3).setResizable(false);
            tbl_hdct.getColumnModel().getColumn(4).setResizable(false);
            tbl_hdct.getColumnModel().getColumn(5).setResizable(false);
            tbl_hdct.getColumnModel().getColumn(6).setResizable(false);
            tbl_hdct.getColumnModel().getColumn(7).setResizable(false);
            tbl_hdct.getColumnModel().getColumn(8).setResizable(false);
        }

        Jpanel_hoadonct.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 850, 180));

        jPanel1.add(Jpanel_hoadonct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 850, 220));

        btn_ct.setText("Chi Tiết");
        btn_ct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ctActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ct, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 110, 30));

        btn_search.setText("Tìm Kiếm");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 120, 40));

        btn_new.setText("Làm Mới");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });
        jPanel1.add(btn_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 130, 40));

        jButton1.setText("Xuất Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 100, -1));

        color1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 960, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(color1, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(color1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_bangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bangMouseClicked
        btn_ct.setVisible(true);
        index = tbl_bang.getSelectedRow();
        id = (int) tbl_bang.getValueAt(index, 0);
    }//GEN-LAST:event_tbl_bangMouseClicked

    private void btn_ctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ctActionPerformed
        btn_new.setVisible(true);
        Jpanel_hoadonct.setVisible(true);
        model = (DefaultTableModel) tbl_hdct.getModel();
        model.setRowCount(0);
        List<HoaDonChiTiet> list = hdct_sv.select_idHD(id);
        for (HoaDonChiTiet hoaDonChiTiet : list) {
            model.addRow(hoaDonChiTiet.todata_hdct());
        }
    }//GEN-LAST:event_btn_ctActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        btn_ct.setVisible(false);
        Jpanel_hoadonct.setVisible(false);
        btn_new.setVisible(true);
        Date startDate = date_1.getDate(); // Lấy ngày bắt đầu từ giao diện
        Date endDate = Date_2.getDate(); // Lấy ngày kết thúc từ giao diện
        List<HoaDon> list_check = hdsv.LichSuHoaDon_ngaythang(a, b, startDate, endDate);
        model = (DefaultTableModel) tbl_bang.getModel();
        model.setRowCount(0);
        for (HoaDon hoaDon : list_check) {
            model.addRow(hoaDon.todata_lshd());
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        Jpanel_hoadonct.setVisible(false);
        btn_ct.setVisible(false);
        btn_new.setVisible(false);
        date_1.setDate(null);
        Date_2.setDate(null);
        fillTable(hdsv.LichSuHoaDon(a, b));
    }//GEN-LAST:event_btn_newActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            Date ngayhientai = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

            XSSFSheet spreadsheet = workbook.createSheet("Danh Sách Hóa Đơn " + sdf.format(ngayhientai));

            XSSFRow row = null;
            Cell cell = null;

            row = spreadsheet.createRow((short) 2);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Danh Sách Hóa Đơn");

            row = spreadsheet.createRow((short) 3);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã Hóa Đơn");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Người Bán");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Người Mua");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Ngày Bán");
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Tổng Tiền");
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("Trạng Thái");

            List<HoaDon> listItem = hdsv.LichSuHoaDon(a, b);
            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");

            for (int i = 0; i < listItem.size(); i++) {
                HoaDon hoadon = listItem.get(i);
                row = spreadsheet.createRow((short) 4 + i);
                row.setHeight((short) 400);
                String ngayBan = df.format(hoadon.getNgayban());
                row.createCell(0).setCellValue(i + 1);
                row.createCell(1).setCellValue(hoadon.getMahD());
                row.createCell(2).setCellValue(hoadon.getNG().getTenND());
                row.createCell(3).setCellValue(hoadon.getKH().getTenKH());
                row.createCell(4).setCellValue(ngayBan);
                row.createCell(5).setCellValue(hoadon.getTongtien());
                row.createCell(6).setCellValue(hoadon.TrangThaiHoadon());
            }

            FileOutputStream out = new FileOutputStream(new File("D:\\game\\Sổ làm việc1.xlsx"));
            workbook.write(out);
            out.close();
            JOptionPane.showMessageDialog(this, "thành công");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_2;
    private javax.swing.JPanel Jpanel_hoadonct;
    private javax.swing.JButton btn_ct;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_search;
    private com.raven.form.Color color1;
    private com.toedter.calendar.JDateChooser date_1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_bang;
    private javax.swing.JTable tbl_hdct;
    // End of variables declaration//GEN-END:variables
}
